### ISSUE TITLE
[dataspace] Enquire about the large datasets backlog for DataSpace/Globus

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-development#799] opened 2023-12-28 15:33 UTC
A number of GitHub issues are marked as open, and in order to ensure that no assistance from RDSS is required, this should first be discussed upon the return of Hannah, Matt, and colleagues within RDSS.

**Comment by matthewjchandler** [comment] 2024-01-11 20:22
There is still a need to make all large (greater than 1 TB) datasets downloadable via Globus.

However, the issue is mitigated by the migration to PDC infrastructure: with everything moving to S3, I expect that it will now at least be possible to download large files via HTTP (whereas it was nearly impossible with DSpace).

What we will want is for large datasets to be migrated one additional step beyond the default, so that they are downloadable via Globus (and the "Download from Globus" button appears on the item page). I consider this part of the overarching migration process, which is still being sorted out.

The highest priority datasets are those currently stored in Dropbox:
- https://dataspace.princeton.edu/handle/88435/dsp013r074x85b
- https://dataspace.princeton.edu/handle/88435/dsp01b8515r30h
- https://dataspace.princeton.edu/handle/88435/dsp01b5644v47m

**Comment by jrgriffiniii** [comment] 2024-01-16 15:11
This can be postponed or closed based upon responses to enquiries passed to RDOS.

**Closed** 2024-03-20 15:19 UTC
Labels: dataspace
