### ISSUE TITLE
Symplectic Elements: Searching queues seem frozen

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/dspace-development#619] opened 2022-03-22 20:17 UTC
## Due Dates

**Proposed Due Date:** 4/8/22

Reason: This affects an aspect of our workflow. We can do other tasks for the time being, but will need this fixed soon as possible.

**Adjusted Due Date:**

Reason:

## Description:

The searching queues in Symplectic are not moving as expected. Please refer to following example and see attached images. 

**Image 1** This shows a search for Andrew Appel, a computer science faculty. As you can see in the image, the searching has been put in queue since Oct. 2021.

**Image2** Newly claimed articles are not showing up in the “Publications in OA policy”, where it should be.

## Acceptance Criteria:

- [ ] Search will operate as expected
- [ ] Newly claimed articles will show in the "Publications in OA policy" section
- [ ] Please reach out to Hannah or Yuan to confirm completion or if you have any follow up questions

![Symplectic_issue1](https://user-images.githubusercontent.com/50670293/159565830-90a106b2-7d1c-4941-a9d7-0819ff25c2d4.jpg)

![Symplectic_image2](https://user-images.githubusercontent.com/50670293/159565845-707febc3-2226-4bbf-83e8-c21c774a7892.jpg)

**Comment by jrgriffiniii** [comment] 2022-03-29 15:11
Job scheduling seems to be completely unavailable for the application:

![image](https://user-images.githubusercontent.com/1443986/160644418-f35e694c-9406-48f5-87e1-79a7b2a911c1.png)

**Comment by jrgriffiniii** [comment] 2022-03-29 15:39
The Synchronization Queues do not seem to be updating:

![image](https://user-images.githubusercontent.com/1443986/160650512-1920ed7d-83bc-463a-99e0-44544ab9e490.png)

**Comment by jrgriffiniii** [comment] 2022-03-29 15:41
Some of the entries enqueued are from March 2022, hence I suspect that the outdate queue entries might need to be purged:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/43d891ba-cfed-4d89-a453-9f01743b3086)

**Comment by jrgriffiniii** [comment] 2022-03-29 16:12
The synchronization for these sources seems to be successful, however I do not see any of the respective queue entries being updated:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/f44596b5-c748-497d-8a7a-69e98fee5d1e)

**Comment by jrgriffiniii** [comment] 2022-03-29 16:20
Enabling and disabling an individual Data Source was, itself, ineffective. Following this attempt, I am now testing the clearing of a queue, and refilling it: ![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/76313fe3-0e16-4e89-8b73-52e213c3779f)

**Comment by jrgriffiniii** [comment] 2022-03-29 16:26
The activity logs for this do indicate that the Publication records are being updated:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/5631928f-cd67-4730-95a0-fd1d6b9a20f1)

**Comment by hhkitsune** [comment] 2022-03-29 21:04
@jrgriffiniii Yuan and I are both still experiencing the frozen search. See image:

![image (4)](https://user-images.githubusercontent.com/50670293/160706735-a3f5ea83-185b-4582-a80a-6cc3c52d1616.png)

**Comment by jrgriffiniii** [comment] 2022-03-31 19:44
Trying to clear and repopulate the search queues for the following data sources has *not* led to a resolution of the problem:

- arXiv
- CiNii EN
- CiNii JP
- Crossref
- DBLP
- Europe PubMed Central
- RePEc
- Scopus
- SSRN
- Web of Science (Lite)

It must also be noted that, for the following two Data Sources, there are currently errors blocking the harvesting of metadata:

- Crossref
- PubMed

**Comment by jrgriffiniii** [comment] 2022-03-31 20:23
This request has been submitted to https://support.symplectic.co.uk/support/tickets/371230. I apologize, as I am not quite certain as to when this might be resolved.

**Comment by jrgriffiniii** [comment] 2022-04-01 19:03
Rebooting the server has not resolved this issue as anticipated, and I have provided the following update to Symplectic Support:

```
Dear Jeff,

I apologize for the delay, the reboot did not successfully resolve this issue.

I did, however, find the following log entries for the "Manage Data Sources":
2022-04-01 12:00:23 [arXiv synchroniser]: 100 postponed Fetch work items reactivated.

2022-04-01 12:00:23 [arXiv synchroniser]: New work found. Waking up...

2022-04-01 12:00:23 [arXiv synchroniser]: Processing priority 10 fetch for a batch of 100 records...

2022-04-01 12:00:25 [arXiv synchroniser]: arXiv made an invalid response.

2022-04-01 12:00:25 [arXiv synchroniser]: Fetch batch errored. Retry postponed until after 4/2/2022 12:00:25 PM.

2022-04-01 12:00:25 [arXiv synchroniser]: Since the arXiv synchroniser was last restarted, 9952 work items have been automatically enqueued, 400 reactivated, 100 successfully processed, 0 discarded and 4 postponed. If no logging has appeared since the last such message, the ongoing work has resulted in no data changes.

2022-04-01 12:00:25 [arXiv synchroniser]: There is currently no more work to do.

2022-04-01 14:29:44 [arXiv synchroniser]: arXiv synchroniser stopped.

2022-04-01 14:54:29: Maximum ETL extract batch size: 20Mb.

2022-04-01 14:54:30 [arXiv synchroniser]: arXiv synchroniser started.

2022-04-01 14:54:30 [arXiv synchroniser]: Object Search queue deactivated.

2022-04-01 14:54:30 [arXiv synchroniser]: Change Check queue deactivated.

2022-04-01 14:54:30 [arXiv synchroniser]: Harvest queue deactivated.

2022-04-01 14:54:30 [arXiv synchroniser]: Push queue deactivated.

2022-04-01 14:54:30 [arXiv synchroniser]: There is currently no more work to do.




Might there be some way of determining whether or not these errors are related to the logged "arXiv made an invalid response" event?




If this is unrelated, please let me know how it might be best to continue trying to diagnose this.

Thank you,
James 
```

**Comment by jrgriffiniii** [comment] 2022-04-04 20:16
A compressed TAR file was generated with the logs from the Elements synchronizer service, and provided to Symplectic Support for detailed analysis.

**Comment by jrgriffiniii** [comment] 2022-04-27 14:57
Given a thorough review of the application logs by Symplectic Support, no clear causes for this error could be readily identified without directly accessing the server environments. As this requires a more direct access to the code base for proper diagnosis, I have scheduled a meeting for 04/28/22 from 14:00 - 15:00 EDT for a screen-sharing session with a support specialist. Should this fail to yield any actionable items for our team, this may need to be delayed until the Digital Science team has begun to undertake the migration for the Elements installations.

**Comment by jrgriffiniii** [comment] 2022-04-28 18:35
After a brief pairing session with Symplectic Support, it was discovered that there are database connectivity issues affecting the server for Elements:

```powershell
2022-04-28 14:07:48: Exception on machine: NetBIOS name "CISDR201W", OS "Microsoft Windows NT 6.2.9200.0" (64-bit)
Software instance: Default, Software Version: 5.14.0.2013, Commit Hash: b1ac109d2f78883a8ae8ff767c364b06b3cb9dc8
Command ""D:\Symplectic\Elements\Scheduler.Service\Scheduler.Service.exe"" (32-bit)
-----------------------------------------------------------------------------------
Log entry ID: fb9d958e-e209-489d-9eec-00057fe26179
Logged at: 14:07:48.941 28/04/22

Level 1:
-------
Exception type: System.Data.SqlClient.SqlException
Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
Stack trace:
at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity, SqlConnectionString, SqlCredential, Object, String, SecureString, Boolean, SqlConnectionString, SessionData, DbConnectionPool, String, Boolean, SqlAuthenticationProviderManager)
at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions, DbConnectionPoolKey, Object, DbConnectionPool, DbConnection, DbConnectionOptions)
at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool, DbConnection, DbConnectionOptions, DbConnectionPoolKey, DbConnectionOptions)
at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection, DbConnectionOptions, DbConnectionInternal)
at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection, DbConnectionOptions, DbConnectionInternal)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection, UInt32, Boolean, Boolean, DbConnectionOptions, DbConnectionInternal&)
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection, TaskCompletionSource<DbConnectionInternal>, DbConnectionOptions, DbConnectionInternal&)
at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection, TaskCompletionSource<DbConnectionInternal>, DbConnectionOptions, DbConnectionInternal, DbConnectionInternal&)
at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection, DbConnectionFactory, TaskCompletionSource<DbConnectionInternal>, DbConnectionOptions)
at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection, DbConnectionFactory, TaskCompletionSource<DbConnectionInternal>, DbConnectionOptions)
at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource<DbConnectionInternal>)
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource<DbConnectionInternal>)
at System.Data.SqlClient.SqlConnection.Open()
at Symplectic.Data.TransactionManager.NewScope(Boolean, Boolean, Nullable<IsolationLevel>) in libraries\Symplectic.Data\GenericTransactionManager.cs:line 224, char 6
at Symplectic.Data.GenericTransactionManager<N, C, A, R, T>.ExecuteReader(C, CommandBehavior, Action) in libraries\Symplectic.Data\GenericTransactionManager.cs:line 932, char 4
at Symplectic.Elements.DataAccess.ElementsDatabase.GetJobs(Nullable<Int32>) in elements\DataAccess\ElementsDatabase.cs:line 383, char 4
at Symplectic.Elements.DataAccess.ElementsDatabase.GetAllJobSchedules() in elements\DataAccess\ElementsDatabase.cs:line 365, char 31
at Symplectic.Elements.Scheduler.Service.Scheduler.UpdateSchedule(OperationSource) in elements\Scheduler.Service\Scheduler.cs:line 208, char 6
at Symplectic.Elements.Scheduler.Service.Scheduler.MainTimerTick(Object) in elements\Scheduler.Service\Scheduler.cs:line 867, char 5

SQL-specific information:

SQL Error:
	Class: 20
	Number: 53
	State: 0
	Provider: .Net SqlClient Data Provider
	Server: 
	Procedure: 
	Line number: 0

Level 2:
-------
Exception type: System.ComponentModel.Win32Exception
Message: The network path was not found
Exception not yet thrown.
```

**Comment by jrgriffiniii** [comment] 2022-04-28 18:37
In response to this, I am afraid that I am going to need to submit a SN@P support request to try and diagnose the database connectivity issues with the OIT.

**Comment by jrgriffiniii** [comment] 2022-04-28 18:46
This is now being tracked with https://princeton.service-now.com/now/workspace/agent/record/incident/6406ee4f874f0d1452d1edfd0ebb3599

**Comment by jrgriffiniii** [comment] 2022-04-28 18:46
This is now being tracked with https://princeton.service-now.com/now/workspace/agent/record/incident/6406ee4f874f0d1452d1edfd0ebb3599

**Comment by jrgriffiniii** [comment] 2022-05-02 19:30
Database connectivity is not blocked from the network firewall, as the following has been reported:

> Consider what has changed in the past 10 days. It appears that "something" happened on Friday April 22, 2022.

> Logrythm (SIEM) search indicates that the firewall is allowing traffic between cisdr201w and cisdr209w

**Comment by jrgriffiniii** [comment] 2022-05-09 13:15
The reindexing jobs are now running *without* raising errors within the system log:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/80534728-8238-4d8b-a347-018c4834b456)

**Comment by jrgriffiniii** [comment] 2022-05-09 13:21
Attempting to restart the index manually does not seem to be working (or, this succeeds silently, and the returns to the `not running` state):

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/af8ca57a-dd3b-444a-a3dd-15f98db438ba)

**Comment by jrgriffiniii** [comment] 2022-05-09 13:26
The failures are being logged within the Windows Server environment, with the following information:

```
Log entry ID: 707b0384-e3e8-4ff6-a14f-492020a9c103
Logged at: 09:21:01.369 09/05/22

Level 1:
-------
Exception type: Symplectic.Elements.DataAccess.ElementsCacheInitialisationException
Message: The application's cache of data could not be initialised. (0 results sets loaded).
Stack trace:
at Symplectic.Elements.DataAccess.ElementsDatabase.GetCache() in elements\DataAccess\ElementsDatabase.cs:line 1946, char 5
at Symplectic.Elements.DataAccess.CacheManager.get_Cache() in elements\DataAccess\CacheManager.cs:line 67, char 6
at Symplectic.Elements.DataEntities.Caching.Cache.get_TheCache() in elements\DataEntities\Caching\Cache.cs:line 211, char 5
at Symplectic.Elements.Emailer.Processes.Email.SendErrorReport(Exception) in elements\Emailer.Processes\Email.cs:line 91, char 5

Level 2:
-------
Exception type: System.Data.SqlClient.SqlException
Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
Stack trace:
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection, UInt32, Boolean, Boolean, DbConnectionOptions, DbConnectionInternal&)
```

I will review the configuration files in order to ensure that there are no outstanding errors.

**Comment by jrgriffiniii** [comment] 2022-05-09 17:04
Currently, there are enqueued jobs being executed (this was not the case from before):

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/8c973bce-3660-4532-8eae-8220836f4803)

I am going to attempt to reproduce the previous behavior.

**Comment by jrgriffiniii** [comment] 2022-05-09 18:27
Unfortunately, following a pairing session, it was discovered that the restored indexing did *not* fully resolve these errors, and that the problematic behavior can still be observed. I will endeavor to continue trying to have this fully restored.

**Comment by jrgriffiniii** [comment] 2022-05-09 19:09
This seems to have been delayed by the indexing job queue, however, the claimed publications are now being successfully indexed:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/3649daeb-e79a-4edf-bb54-8741a8d643c1)

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/5699a3dd-3cb6-4e32-bf73-581d55941f93)

**Comment by jrgriffiniii** [comment] 2022-05-10 13:56
The reindexing seems to be functioning as expected now:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/1177fbd3-3ac3-4876-9daa-28f8d352e6fb)

**Comment by jrgriffiniii** [comment] 2022-05-10 13:57
This also confirms my suspicions, and should permit me to proceed with closing this issue:

![image.png](https://images.zenhubusercontent.com/5b5b6aed981c3204c9ed06c8/7c371edd-278b-4fde-9d6d-27101181044d)

**Closed by jrgriffiniii** 2022-05-10 13:57 UTC
Labels: symplectic elements
