### ISSUE TITLE
Incorrect display of names with diacritics (character encoding issues)

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/dspace-development#267] opened 2021-01-13 13:48 UTC
There seems to be an issue with how DataSpace is handling diacritics. I'm not sure how far the problem goes.

For now, what I know is that a submitter has asked to fix how their name is displayed within the submission portal: currently, an "é" is being replaced with "Ã©". I also saw the same issue with the name in an email message about the submission.

I don't want to suggest anyone give their name stripped of diacritics unless I absolutely have to--that seems insensitive. And I suspect there may be a deeper issue here with DataSpace's (or DSpace's) use of Unicode.

**ACCEPTANCE CRITERIA**
- [ ] Investigate whether this is a problem in DSpace, or a problem with the data we get from Princeton CAS

**Comment by hectorcorrea** [comment] 2021-11-02 18:18
This is a duplicate of #275

**Closed by hectorcorrea** 2021-11-02 18:18 UTC
Labels: bug, dataspace
